const USER_OR_PASSWORD_IS_NOT_EXISTS = 'user/USER_OR_PASSWORD_IS_NOT_EXISTS'
const USER_ALREADY_EXISTS = 'user/USER_ALREADY_EXISTS'
const USERNAME_OR_PASSWORD_IS_MUST = 'user/USERNAME_OR_PASSWORD_IS_MUST'

module.exports = {
    USER_OR_PASSWORD_IS_NOT_EXISTS,
    USER_ALREADY_EXISTS,
    USERNAME_OR_PASSWORD_IS_MUST
}